import Link from "next/link";
import { History, Leaf, Sprout, Truck } from "lucide-react";
import { Container } from "@/components/layout/container";
import { Logo } from "@/components/shared/logo";
import { getCatalogHref } from "@/lib/catalog";

const confianza = [{ icon: History, titulo: "14 años de experiencia" }, { icon: Sprout, titulo: "Hidropónicos" }, { icon: Truck, titulo: "Abastecimiento confiable" }, { icon: Leaf, titulo: "Compromiso sustentable" }];
const productos = [{ label: "Catálogo", href: "/catalogo" }, { label: "Hidropónicos", href: getCatalogHref({ category: "Hidropónicos" }) }, { label: "Verduras y hortalizas", href: getCatalogHref({ category: "Verduras y hortalizas" }) }, { label: "Frutas", href: getCatalogHref({ category: "Frutas" }) }, { label: "Hierbas y especias", href: getCatalogHref({ category: "Hierbas y especias" }) }];

export function PublicFooter() {
  return <footer className="mt-auto border-t border-border bg-secondary/55"><Container className="py-10 sm:py-12"><div className="grid gap-8 lg:grid-cols-[1.25fr_.8fr_.8fr] lg:gap-12"><section className="max-w-md"><Logo className="inline-block rounded-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50" /><p className="mt-4 text-base font-medium text-foreground">Abastecimiento de productos frescos para negocios y empresas.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Hidropónicos, verduras, frutas y más.</p><div className="mt-5"><Link href="/iniciar-sesion" className="inline-flex min-h-11 items-center rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground outline-none focus-visible:ring-3 focus-visible:ring-ring/50">Acceso clientes</Link></div></section><nav aria-label="Productos"><h2 className="text-sm font-semibold text-foreground">Productos</h2><ul className="mt-3 space-y-2">{productos.map((item) => <li key={item.href}><Link href={item.href} className="rounded-sm text-sm text-muted-foreground outline-none hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring">{item.label}</Link></li>)}</ul></nav><section><h2 className="text-sm font-semibold text-foreground">Hidro Leufú</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">14 años abasteciendo a nuestros clientes con productos frescos.</p><p className="mt-3 text-sm leading-6 text-muted-foreground">¿Ya eres cliente? Ingresa para revisar tu cuenta.</p></section></div><section aria-label="Señales de confianza" className="mt-9 grid grid-cols-2 gap-3 border-y border-border py-5 sm:grid-cols-4">{confianza.map(({ icon: Icon, titulo }) => <div key={titulo} className="flex items-center gap-2 text-sm text-muted-foreground"><Icon className="size-4 shrink-0 text-accent" aria-hidden="true" /><span>{titulo}</span></div>)}</section><div className="pt-5 text-sm text-muted-foreground">© {new Date().getFullYear()} Hidro Leufú. Todos los derechos reservados.</div></Container></footer>;
}
