export const ROUTES = {
  home: "/",
  catalog: "/catalogo",
  cart: "/carrito",
  checkout: "/checkout",
  orderConfirmation: (id: string) => `/pedido/confirmacion/${id}`,
  account: "/mi-cuenta",
  accountOrders: "/mi-cuenta/pedidos",
  accountAddresses: "/mi-cuenta/direcciones",
  accountBenefits: "/mi-cuenta/beneficios",
  admin: "/admin",
  adminProducts: "/admin/productos",
  adminCategories: "/admin/categorias",
  adminHomeSections: "/admin/secciones-inicio",
  adminOrders: "/admin/pedidos",
  adminCustomers: "/admin/clientes",
  adminDeliveries: "/admin/entregas",
  adminRoutes: "/admin/rutas",
  adminSettings: "/admin/configuracion",
  adminNewProduct: "/admin/productos/nuevo",
  adminNewCategory: "/admin/categorias/nueva",
  adminNewSubcategory: "/admin/subcategorias/nueva",
  product: (slug: string) => `/catalogo/${slug}`,
  customerOrder: (id: string) => `/mi-cuenta/pedidos/${id}`,
  newCustomerAddress: "/mi-cuenta/direcciones/nueva",
  editCustomerAddress: (id: string) => `/mi-cuenta/direcciones/${id}/editar`,
  adminOrder: (id: string) => `/admin/pedidos/${id}`,
  adminCustomer: (id: string) => `/admin/clientes/${id}`,
  adminProduct: (id: string) => `/admin/productos/${id}`,
  adminCategory: (id: string) => `/admin/categorias/${id}`,
  adminSubcategory: (id: string) => `/admin/subcategorias/${id}`,
} as const;
