-- Seed reproducible del catálogo real definido en src/mocks/products.ts y categories.ts.
-- No carga imágenes: el frontend actual sólo declara imageFallback, no rutas reales.

insert into public.categorias (slug, nombre, descripcion, activa, orden)
values
  ('hidroponicos', 'Hidropónicos', 'Cultivos frescos seleccionados.', true, 1),
  ('verduras-hortalizas', 'Verduras y hortalizas', 'Variedad fresca para cada pedido.', true, 2),
  ('frutas', 'Frutas', 'Frutas frescas en distintos formatos.', true, 3),
  ('hierbas-especias', 'Hierbas y especias', 'Hierbas y especias para complementar tus preparaciones.', true, 4),
  ('formatos-cajas', 'Formatos y cajas', 'Formatos comerciales para distintos pedidos.', true, 5),
  ('otros', 'Otros', 'Otros productos disponibles.', true, 6)
on conflict (slug) do update set
  nombre = excluded.nombre, descripcion = excluded.descripcion, activa = excluded.activa, orden = excluded.orden;

with datos (slug, categoria_slug, nombre, descripcion, activo, disponible, destacado, mas_vendido, nuevo, orden) as (
  values
    ('albahaca-en-rama', 'hidroponicos', 'Albahaca en rama', 'Albahaca en rama.', true, true, true, true, false, 1),
    ('berro-hidroponico', 'hidroponicos', 'Berro hidropónico', 'Berro hidropónico.', true, true, true, true, false, 2),
    ('ciboulette-75-gr', 'hidroponicos', 'Ciboulette 75 gr', 'Ciboulette 75 gr.', true, true, false, true, false, 3),
    ('docena-de-ciboulette', 'hidroponicos', 'Docena de ciboulette', 'Docena de ciboulette.', true, true, false, false, false, 4),
    ('flores-comestibles-50-und', 'hidroponicos', 'Flores comestibles 50 und', 'Flores comestibles 50 und.', true, true, true, true, false, 5),
    ('jengibre', 'hidroponicos', 'Jengibre', 'Jengibre.', true, true, false, false, false, 6),
    ('lechuga-hidroponica', 'hidroponicos', 'Lechuga hidropónica', 'Lechuga hidropónica.', true, true, true, true, false, 7),
    ('microgreens-50-gr', 'hidroponicos', 'Microgreens 50 gr (brotes)', 'Microgreens 50 gr (brotes).', true, true, true, true, false, 8),
    ('mix-de-hojas-mizuna-y-mostaza', 'hidroponicos', 'Mix de hojas (mizuna y mostaza)', 'Mix de hojas (mizuna y mostaza).', true, true, false, false, false, 9),
    ('romero-fresco', 'hidroponicos', 'Romero fresco', 'Romero fresco.', true, true, false, false, false, 10),
    ('rucula', 'hidroponicos', 'Rúcula', 'Rúcula.', true, true, false, true, false, 11),
    ('tomate-cherry', 'hidroponicos', 'Tomate cherry', 'Tomate cherry.', true, true, false, true, false, 12),
    ('aji-verde', 'verduras-hortalizas', 'Ají verde', 'Ají verde.', true, true, false, false, false, 13),
    ('ajo', 'verduras-hortalizas', 'Ajo', 'Ajo.', true, true, false, false, false, 14),
    ('apio', 'verduras-hortalizas', 'Apio', 'Apio.', true, true, false, false, true, 15),
    ('berenjena', 'verduras-hortalizas', 'Berenjena', 'Berenjena.', true, true, false, false, false, 16),
    ('betarraga', 'verduras-hortalizas', 'Betarraga', 'Betarraga.', true, true, false, false, false, 17),
    ('brocoli', 'verduras-hortalizas', 'Brócoli', 'Brócoli.', true, true, false, false, false, 18),
    ('cebolla-blanca', 'verduras-hortalizas', 'Cebolla blanca', 'Cebolla blanca.', true, true, false, false, false, 19),
    ('cebolla-morada', 'verduras-hortalizas', 'Cebolla morada', 'Cebolla morada.', true, true, false, false, false, 20),
    ('coliflor', 'verduras-hortalizas', 'Coliflor', 'Coliflor.', true, true, false, false, false, 21),
    ('escarola', 'verduras-hortalizas', 'Escarola', 'Escarola.', true, true, false, false, false, 22),
    ('espinaca', 'verduras-hortalizas', 'Espinaca', 'Espinaca.', true, true, false, false, false, 23),
    ('lechuga-chilena', 'verduras-hortalizas', 'Lechuga chilena', 'Lechuga chilena.', true, true, false, false, false, 24),
    ('papa-camote', 'verduras-hortalizas', 'Papa camote', 'Papa camote.', true, true, false, false, false, 25),
    ('papa', 'verduras-hortalizas', 'Papa', 'Papa.', true, true, false, false, false, 26),
    ('pepino-verdura', 'verduras-hortalizas', 'Pepino verdura', 'Pepino verdura.', true, true, false, false, false, 27),
    ('pimenton-amarillo', 'verduras-hortalizas', 'Pimentón amarillo', 'Pimentón amarillo.', true, true, false, false, false, 28),
    ('pimenton-rojo-primera', 'verduras-hortalizas', 'Pimentón rojo 1era', 'Pimentón rojo 1era.', true, true, false, false, false, 29),
    ('pimenton-verde-primera', 'verduras-hortalizas', 'Pimentón verde 1era', 'Pimentón verde 1era.', true, true, false, false, false, 30),
    ('rabano', 'verduras-hortalizas', 'Rábano', 'Rábano.', true, true, false, false, false, 31),
    ('repollo-morado', 'verduras-hortalizas', 'Repollo morado', 'Repollo morado.', true, true, false, false, false, 32),
    ('repollo-verde', 'verduras-hortalizas', 'Repollo verde', 'Repollo verde.', true, true, false, false, false, 33),
    ('tomate-primera', 'verduras-hortalizas', 'Tomate primera', 'Tomate primera.', true, true, false, false, true, 34),
    ('zanahoria', 'verduras-hortalizas', 'Zanahoria', 'Zanahoria.', true, true, false, false, false, 35),
    ('zapallo-camote', 'verduras-hortalizas', 'Zapallo camote', 'Zapallo camote.', true, true, false, false, false, 36),
    ('aji-amarillo', 'verduras-hortalizas', 'Ají amarillo', 'Ají amarillo.', true, true, false, false, true, 37),
    ('italiano', 'verduras-hortalizas', 'Italiano', 'Italiano.', true, true, false, false, false, 38),
    ('limon-camote-malla', 'frutas', 'Limón camote malla', 'Limón camote malla.', true, true, false, false, false, 39),
    ('limon-normal-malla', 'frutas', 'Limón normal malla', 'Limón normal malla.', true, true, false, false, false, 40),
    ('limon-sutil', 'frutas', 'Limón sutil', 'Limón sutil.', true, true, false, false, false, 41),
    ('mango', 'frutas', 'Mango', 'Mango.', true, true, false, false, false, 42),
    ('manzana-roja-o-verde', 'frutas', 'Manzana roja o verde', 'Manzana roja o verde.', true, true, false, false, false, 43),
    ('naranja', 'frutas', 'Naranja', 'Naranja.', true, true, false, false, false, 44),
    ('palta-peruana-1ra', 'frutas', 'Palta peruana 1ra', 'Palta peruana 1ra.', true, true, false, false, false, 45),
    ('pina', 'frutas', 'Piña', 'Piña.', true, true, false, false, false, 46),
    ('platano', 'frutas', 'Plátano', 'Plátano.', true, true, false, false, false, 47),
    ('pomelo', 'frutas', 'Pomelo', 'Pomelo.', true, true, false, false, false, 48),
    ('platano-macho', 'frutas', 'Plátano macho', 'Plátano macho.', true, true, false, false, true, 49),
    ('mandarina', 'frutas', 'Mandarina', 'Mandarina.', true, true, false, false, false, 50),
    ('kiwi', 'frutas', 'Kiwi', 'Kiwi.', true, true, false, false, false, 51),
    ('cebollin', 'hierbas-especias', 'Cebollín', 'Cebollín.', true, true, false, false, false, 52),
    ('champinon', 'hierbas-especias', 'Champiñón', 'Champiñón.', true, true, false, false, false, 53),
    ('cilantro', 'hierbas-especias', 'Cilantro', 'Cilantro.', true, true, false, false, false, 54),
    ('perejil', 'hierbas-especias', 'Perejil', 'Perejil.', true, true, false, false, false, 55),
    ('semilla-de-mostaza', 'hierbas-especias', 'Semilla de mostaza', 'Semilla de mostaza.', true, true, false, false, false, 56),
    ('anis-estrellado', 'hierbas-especias', 'Anís estrellado', 'Anís estrellado.', true, true, false, false, false, 57),
    ('cebolla-blanca-malla', 'formatos-cajas', 'Cebolla blanca malla', 'Cebolla blanca malla.', true, true, false, false, false, 58),
    ('cebolla-morada-malla', 'formatos-cajas', 'Cebolla morada malla', 'Cebolla morada malla.', true, true, false, false, false, 59),
    ('paquete-cebollin-10-und', 'formatos-cajas', 'Paquete cebollín 10 und', 'Paquete cebollín 10 und.', true, true, false, false, false, 60),
    ('escarola-caja', 'formatos-cajas', 'Escarola caja', 'Escarola caja.', true, true, false, false, false, 61),
    ('naranja-malla-15-kg', 'formatos-cajas', 'Naranja malla 15 kg', 'Naranja malla 15 kg.', true, true, false, false, false, 62),
    ('saco-papa-lavada-25-kg', 'formatos-cajas', 'Saco papa lavada 25 kg', 'Saco papa lavada 25 kg.', true, true, false, false, false, 63),
    ('saco-de-papa-sucia-25-kg', 'formatos-cajas', 'Saco de papa sucia 25 kg', 'Saco de papa sucia 25 kg.', true, true, false, false, false, 64),
    ('tomate-primera-caja-17-kg', 'formatos-cajas', 'Tomate primera caja 17 kg', 'Tomate primera caja 17 kg.', true, true, false, false, true, 65),
    ('caja-de-italiano', 'formatos-cajas', 'Caja de italiano', 'Caja de italiano.', true, true, false, false, false, 66),
    ('caja-de-huevo', 'formatos-cajas', 'Caja de huevo', 'Caja de huevo.', true, true, false, false, false, 67),
    ('miel', 'otros', 'Miel', 'Miel.', true, true, false, false, false, 68)
)
insert into public.productos (categoria_id, nombre, slug, descripcion, ruta_imagen, unidad_base, activo, disponible, destacado, mas_vendido, nuevo, orden)
select c.id, d.nombre, d.slug, d.descripcion, null, 'comercial', d.activo, d.disponible, d.destacado, d.mas_vendido, d.nuevo, d.orden
from datos d join public.categorias c on c.slug = d.categoria_slug
on conflict (slug) do update set
  categoria_id = excluded.categoria_id, nombre = excluded.nombre, descripcion = excluded.descripcion, ruta_imagen = excluded.ruta_imagen,
  unidad_base = excluded.unidad_base, activo = excluded.activo, disponible = excluded.disponible, destacado = excluded.destacado,
  mas_vendido = excluded.mas_vendido, nuevo = excluded.nuevo, orden = excluded.orden;

with datos (producto_slug, nombre, cantidad, unidad, precio_neto, precio_final, orden) as (
  values
    ('albahaca-en-rama', '1 UND', 1, 'UND', 1000, 1190, 1),
    ('berro-hidroponico', '1 KG', 1, 'KG', 9000, 10710, 2),
    ('ciboulette-75-gr', '75 GR', 75, 'GR', 500, 595, 3),
    ('docena-de-ciboulette', 'Docena (12 UND)', 12, 'UND', 5000, 5950, 4),
    ('flores-comestibles-50-und', '50 UND', 50, 'UND', 2500, 2975, 5),
    ('jengibre', '1 KG', 1, 'KG', 4000, 4760, 6),
    ('lechuga-hidroponica', '1 UND', 1, 'UND', 700, 833, 7),
    ('microgreens-50-gr', '50 GR', 50, 'GR', 2500, 2975, 8),
    ('mix-de-hojas-mizuna-y-mostaza', '1 KG', 1, 'KG', 9000, 10710, 9),
    ('romero-fresco', '100 GR', 100, 'GR', 1500, 1785, 10),
    ('rucula', '1 KG', 1, 'KG', 9000, 10710, 11),
    ('tomate-cherry', '1 KG', 1, 'KG', 2500, 2975, 12),
    ('aji-verde', '1 KG', 1, 'KG', 4000, 4760, 13),
    ('ajo', '1 UND', 1, 'UND', 250, 298, 14),
    ('apio', '1 UND', 1, 'UND', 1200, 1428, 15),
    ('berenjena', '1 UND', 1, 'UND', 600, 714, 16),
    ('betarraga', '1 UND', 1, 'UND', 1500, 1785, 17),
    ('brocoli', '1 UND', 1, 'UND', 1200, 1428, 18),
    ('cebolla-blanca', '1 KG', 1, 'KG', 800, 952, 19),
    ('cebolla-morada', '1 KG', 1, 'KG', 1500, 1785, 20),
    ('coliflor', '1 UND', 1, 'UND', 1500, 1785, 21),
    ('escarola', '1 UND', 1, 'UND', 1000, 1190, 22),
    ('espinaca', '1 UND', 1, 'UND', 800, 952, 23),
    ('lechuga-chilena', '1 UND', 1, 'UND', 1000, 1190, 24),
    ('papa-camote', '1 KG', 1, 'KG', 2500, 2975, 25),
    ('papa', '1 KG', 1, 'KG', 950, 1131, 26),
    ('pepino-verdura', '1 UND', 1, 'UND', 500, 595, 27),
    ('pimenton-amarillo', '1 UND', 1, 'UND', 900, 1071, 28),
    ('pimenton-rojo-primera', '1 UND', 1, 'UND', 1000, 1190, 29),
    ('pimenton-verde-primera', '1 UND', 1, 'UND', 800, 952, 30),
    ('rabano', '1 UND', 1, 'UND', 600, 714, 31),
    ('repollo-morado', '1 UND', 1, 'UND', 2000, 2380, 32),
    ('repollo-verde', '1 UND', 1, 'UND', 2000, 2380, 33),
    ('tomate-primera', '1 KG', 1, 'KG', 1200, 1428, 34),
    ('zanahoria', '1 KG', 1, 'KG', 1400, 1666, 35),
    ('zapallo-camote', '1 KG', 1, 'KG', 2500, 2975, 36),
    ('aji-amarillo', '1 KG', 1, 'KG', 8000, 9520, 37),
    ('italiano', '1 UND', 1, 'UND', 600, 714, 38),
    ('limon-camote-malla', '1 UND', 1, 'UND', 4000, 4760, 39),
    ('limon-normal-malla', '1 UND', 1, 'UND', 4500, 5355, 40),
    ('limon-sutil', '1 KG', 1, 'KG', 2800, 3332, 41),
    ('mango', '1 UND', 1, 'UND', 1500, 1785, 42),
    ('manzana-roja-o-verde', '1 KG', 1, 'KG', 1500, 1785, 43),
    ('naranja', '1 KG', 1, 'KG', 700, 833, 44),
    ('palta-peruana-1ra', '1 KG', 1, 'KG', 3000, 3570, 45),
    ('pina', '1 UND', 1, 'UND', 2800, 3332, 46),
    ('platano', '1 KG', 1, 'KG', 1200, 1428, 47),
    ('pomelo', '1 KG', 1, 'KG', 1000, 1190, 48),
    ('platano-macho', '1 KG', 1, 'KG', 2500, 2975, 49),
    ('mandarina', '1 KG', 1, 'KG', 1000, 1190, 50),
    ('kiwi', '1 KG', 1, 'KG', 1500, 1785, 51),
    ('cebollin', '1 UND', 1, 'UND', 700, 833, 52),
    ('champinon', '1 KG', 1, 'KG', 8000, 9520, 53),
    ('cilantro', '1 UND', 1, 'UND', 900, 1071, 54),
    ('perejil', '1 UND', 1, 'UND', 600, 714, 55),
    ('semilla-de-mostaza', '1 KG', 1, 'KG', 5500, 6545, 56),
    ('anis-estrellado', '1 KG', 1, 'KG', 18000, 21420, 57),
    ('cebolla-blanca-malla', '1 UND', 1, 'UND', 12000, 14280, 58),
    ('cebolla-morada-malla', '1 UND', 1, 'UND', 20000, 23800, 59),
    ('paquete-cebollin-10-und', 'Paquete 10 UND', 10, 'UND', 7000, 8330, 60),
    ('escarola-caja', '1 UND', 1, 'UND', 13000, 15470, 61),
    ('naranja-malla-15-kg', 'Malla 15 KG', 15, 'KG', 7000, 8330, 62),
    ('saco-papa-lavada-25-kg', 'Saco 25 KG', 25, 'KG', 22000, 26180, 63),
    ('saco-de-papa-sucia-25-kg', 'Saco 25 KG', 25, 'KG', 19000, 22610, 64),
    ('tomate-primera-caja-17-kg', 'Caja 17 KG', 17, 'KG', 19000, 22610, 65),
    ('caja-de-italiano', '1 UND', 1, 'UND', 22000, 26180, 66),
    ('caja-de-huevo', '1 UND', 1, 'UND', 36000, 42840, 67),
    ('miel', '1 KG', 1, 'KG', 6000, 7140, 68)
)
insert into public.presentaciones_producto (producto_id, nombre, cantidad, unidad, precio_neto, precio_final, es_principal, activa, orden)
select p.id, d.nombre, d.cantidad, d.unidad, d.precio_neto, d.precio_final, true, true, d.orden
from datos d join public.productos p on p.slug = d.producto_slug
on conflict (producto_id) where es_principal and activa do update set
  nombre = excluded.nombre, cantidad = excluded.cantidad, unidad = excluded.unidad, precio_neto = excluded.precio_neto,
  precio_final = excluded.precio_final, orden = excluded.orden;


